name = "mauntic-campaign"
compatibility_date = "2026-02-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "270bd3689e8846e7ae61d3e1674bfba0"

[[kv_namespaces]]
binding = "KV"
id = "107300e1a7004921b6b4fc22d098af9a"

[[queues.producers]]
binding = "EVENTS"
queue = "mauntic-campaign-events"

[[queues.consumers]]
queue = "mauntic-campaign-events"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "mauntic-campaign-events-dlq"
