name = "mauntic-billing"
compatibility_date = "2026-02-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[[hyperdrive]]
binding = "DB"
id = "72ed37f34f16429088564b927eb093bc"

[[durable_objects.bindings]]
name = "TENANT_CACHE"
class_name = "TenantContextDurableObject"
script_name = "mauntic-gateway"

[vars]
APP_DOMAIN = "zeluto.com"
