name = "mauntic-crm"
compatibility_date = "2026-02-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[[hyperdrive]]
binding = "DB"
id = "placeholder"

[[kv_namespaces]]
binding = "KV"
id = "placeholder"

[[queues.producers]]
binding = "EVENTS"
queue = "mauntic-crm-events"
