name = "mauntic-identity"
compatibility_date = "2026-02-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[[hyperdrive]]
binding = "DB"
id = "72ed37f34f16429088564b927eb093bc"
localConnectionString = "postgresql://neondb_owner:npg_8KTCgZUb1Dvl@ep-jolly-pine-ai35q07s-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require"

[[kv_namespaces]]
binding = "KV"
id = "107300e1a7004921b6b4fc22d098af9a"

[[durable_objects.bindings]]
name = "TENANT_CACHE"
class_name = "TenantContextDurableObject"
script_name = "mauntic-tenant-cache"

[vars]
APP_DOMAIN = "zeluto.com"
BETTER_AUTH_URL = "https://zeluto.com"

[[analytics_engine_datasets]]
binding = "LOGS_DATASET"
dataset = "mauntic_logs"
